/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: [
    './App.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontSize: {
        'display1-bold': ['28px', {lineHeight: '42px'}, {fontWeight: '700'}],
        'display1-medium': ['28px', {lineHeight: '42px'}, {fontWeight: '500'}],
        'head1-bold': ['24px', {lineHeight: '36px'}, {fontWeight: '700'}],
        'head1-medium': ['24px', {lineHeight: '36px'}, {fontWeight: '500'}],
        'head1-regular': ['24px', {lineHeight: '36px'}, {fontWeight: '400'}],
        'head2-bold': [
          '20px',
          {lineHeight: '30px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '700'},
        ],
        'head2-medium': [
          '20px',
          {lineHeight: '30px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '500'},
        ],
        'head2-regular': [
          '20px',
          {lineHeight: '30px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '400'},
        ],
        'title1-bold': [
          '18px',
          {lineHeight: '27px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '700'},
        ],
        'title1-medium': [
          '18px',
          {lineHeight: '27px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '500'},
        ],
        'title1-regular': [
          '18px',
          {lineHeight: '27px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '400'},
        ],
        'label1-bold': [
          '16px',
          {lineHeight: '24px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '700'},
        ],
        'label1-medium': [
          '16px',
          {lineHeight: '24px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '500'},
        ],
        'label1-regular': [
          '16px',
          {lineHeight: '24px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '400'},
        ],
        'body1-bold': [
          '15px',
          {lineHeight: '23px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '700'},
        ],
        'body1-medium': [
          '15px',
          {lineHeight: '23px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '500'},
        ],
        'body1-regular': [
          '15px',
          {lineHeight: '23px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '400'},
        ],
        'body2-bold': [
          '14px',
          {lineHeight: '21px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '700'},
        ],
        'body2-medium': [
          '14px',
          {lineHeight: '21px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '500'},
        ],
        'body2-regular': [
          '14px',
          {lineHeight: '21px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '400'},
        ],
        'caption1-bold': [
          '12px',
          {lineHeight: '18px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '700'},
        ],
        'caption1-medium': [
          '12px',
          {lineHeight: '18px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '500'},
        ],
        'caption1-regular': [
          '12px',
          {lineHeight: '18px'},
          {letterSpacing: '-1.5%'},
          {fontWeight: '400'},
        ],
      },
      colors: {
        'primary-red': '#FA3E6E',
        'primary-light-red': '#FFBBCC',
        'primary-dark-red': '#A30033',
        'secondary-blue': '#5A5FFF',
        'secondary-mint': '#ABEEC6',
        'secondary-black': '#0E0E0E',
        'grey-white': '#FDFDFD',
        'grey-70': '#F7F8F9',
        'grey-60': '#C5C8CE',
        'grey-50': '999FA4',
        'grey-40': '#5A6166',
        'grey-20': '#41474C',
        'grey-15': '#2E363A',
        'grey-10': '#1E2427',
        'grey-05': '#171B1C',
        'background-normal': '#0E0E0E',
        'background-elevated': '#0E0E0E80',
        'text-primary': '#FDFDFD',
        'text-secondary': '#999FA4',
      },
    },
  },
  plugins: [],
};
